name: sqdron # you probably want to 'snapcraft register <name>'
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Something # 79 char long summary
description: |
  All right.

grade: stable
confinement: strict

plugs:
  support:
    interface: docker-support
  privileged:
    interface: docker-support
    privileged-containers: true
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: docker-env

apps: 
  sqdron:
    command: bin/agentlocal
    plugs: [network, network-bind, docker-executables, docker-cli]
  server:
    command: bin/server
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, docker-executables, docker-cli]


parts:
  sqdron:
    plugin: go
    source: .
  server:
    plugin: go
    source: ../server

    

