#!/bin/sh

if [ "$SNAP_ARCH" = "amd64" ]; then
    ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
    ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
    ARCH="aarch64-linux-gnu"
else
    ARCH="$SNAP_ARCH-linux-gnu"
fi

export DOCKER_ENV="$SNAP/docker-env"
export PATH="$DOCKER_ENV/usr/sbin:$DOCKER_ENV/usr/bin:$DOCKER_ENV/sbin:$DOCKER_ENV/bin:$PATH"
export LD_LIBRARY_PATH="$DOCKER_ENV/lib:$DOCKER_ENV/usr/lib:$DOCKER_ENV/lib/$ARCH:$DOCKER_ENV/usr/lib/$ARCH:$LD_LIBRARY_PATH"
export PYTHONPATH="$DOCKER_ENV/lib/python2.7/site-packages"

if [ "$1" = 'docker-compose' ]; then
    cmd="$1"
    shift
    set -- python2 "$(which "$cmd")" "$@"
fi

exec "$@"
